version: '3'

services:
  proxy:
    image: nginx
    restart: always
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./public:/public:ro
    - ./fullchain.pem:/etc/certificates/fullchain.pem:ro
    - ./privkey.pem:/etc/certificates/privkey.pem:ro
    ports:
    - 80:80
    - 443:443
  generator-server:
    image: hsldevcom/hsl-map-generator-server
    restart: always
    expose:
    - 8000
  generator-ui:
    image: hsldevcom/hsl-map-generator-ui
    restart: always
    expose:
    - 3000
  publisher-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
    - 5432
    volumes:
    - ./postgres:/var/lib/postgresql/data
  publisher:
    image: hsldevcom/hsl-map-publisher
    environment:
      PG_CONNECTION_STRING: postgres://postgres:postgres@publisher-postgres:5432/postgres
      PG_JORE_CONNECTION_STRING: postgres://postgres:postgres@jore-postgis:5432/postgres
    depends_on:
    - publisher-postgres
    - jore-postgis
    restart: always
    expose:
    - 4000
    shm_size: '1gb'
    volumes:
    - ./fonts:/fonts:ro
    - ./output:/output
  publisher-ui:
    image: hsldevcom/hsl-map-publisher-ui
    restart: always
    expose:
    - 5000
  site:
    image: hsldevcom/hsl-map-site
    restart: always
    expose:
    - 4000
  web-ui:
    image: hsldevcom/hsl-map-web-ui
    restart: always
    expose:
    - 3000
  route-map-poc:
    image: hsldevcom/hsl-route-map-poc
    restart: always
    expose:
    - 3000
  jore-postgis:
    image: mdillon/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
    - 5432
  jore-postgis-i2:
    image: mdillon/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
    - 5432
  jore-graphql-import:
    image: hsldevcom/jore-graphql-import
    environment:
      PG_CONNECTION_STRING: postgres://postgres:postgres@jore-postgis:5432/postgres
    environment:
      - USERNAME=${FTP_USERNAME}
      - PASSWORD=${FTP_PASSWORD}
    depends_on:
    - jore-postgis
  jore-geometry-matcher:
    image: hsldevcom/jore-geometry-matcher
    environment:
      PG_CONNECTION_STRING: postgres://postgres:postgres@jore-postgis:5432/postgres
    depends_on:
    - jore-postgis
  jore-graphql:
    image: hsldevcom/jore-graphql
    restart: always
    environment:
      PG_CONNECTION_STRING: postgres://postgres:postgres@jore-postgis:5432/postgres
    depends_on:
    - jore-postgis
    expose:
    - 5000
  jore-tileserver:
    image: hsldevcom/jore-tileserver
    restart: always
    environment:
      PG_CONNECTION_STRING: postgres://postgres:postgres@jore-postgis:5432/postgres
    depends_on:
    - jore-postgis
    expose:
    - 3000
  jore-graphql-i2:
    image: hsldevcom/jore-graphql
    restart: always
    environment:
      PG_CONNECTION_STRING: postgres://postgres:postgres@jore-postgis-i2:5432/postgres
    depends_on:
    - jore-postgis-i2
    expose:
    - 5000
  jore-tileserver-i2:
    image: hsldevcom/jore-tileserver
    restart: always
    environment:
      PG_CONNECTION_STRING: postgres://postgres:postgres@jore-postgis-i2:5432/postgres
    depends_on:
    - jore-postgis
    expose:
    - 3000
