version: '2'

services:
  proxy:
    image: nginx
    restart: always
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./public:/public:ro
    - output:/output
    ports:
    - 80:80
  generator-server:
    build: https://github.com/HSLdevcom/hsl-map-generator-server.git
    restart: always
    environment:
      FONTSTACK_PASSWORD: ${FONTSTACK_PASSWORD}
    ports:
    - 8000:8000
  generator-ui:
    build: https://github.com/HSLdevcom/hsl-map-generator-ui.git
    restart: always
    ports:
    - 3000:3000
  publisher:
    build: https://github.com/HSLdevcom/hsl-map-publisher.git
    restart: always
    ports:
    - 5000:5000
    volumes:
    - ./fonts:/fonts:ro
    - output:/output
  site:
    build: https://github.com/HSLdevcom/hsl-map-site.git
    restart: always
    ports:
    - 5050:4000
  web-ui:
    build:
      context: https://github.com/HSLdevcom/hsl-map-web-ui.git
      args:
        ROOT_PATH: /kuljettaja
    restart: always
    ports:
    - 4000:3000
  jore-postgis:
    image: mdillon/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
    - 5432
  jore-graphql-import:
    build: https://github.com/HSLdevcom/jore-graphql-import.git
    environment:
      PG_CONNECTION_STRING: postgres://postgres:postgres@jore-postgis:5432/postgres
    depends_on:
    - jore-postgis
  jore-graphql:
    build: https://github.com/HSLdevcom/jore-graphql.git
    restart: always
    environment:
      PG_CONNECTION_STRING: postgres://postgres:postgres@jore-postgis:5432/postgres
    depends_on:
    - jore-postgis
    ports:
    - 8080:5000
volumes:
  output: {}
