version: '2'

services:
  proxy:
    image: nginx
    restart: always
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80
  generator-server:
    build: https://github.com/HSLdevcom/hsl-map-generator-server.git
    restart: always
    ports:
    - 8000:8000
  generator-ui:
    build: https://github.com/HSLdevcom/hsl-map-generator-ui.git
    restart: always
    ports:
    - 3000:3000
  publisher:
    build: https://github.com/HSLdevcom/hsl-map-publisher.git
    restart: always
    ports:
    - 5000:5000
    volumes:
    - ./fonts:/fonts
  web-ui:
    build:
      context: https://github.com/HSLdevcom/hsl-map-web-ui.git
      args:
        ROOT_PATH: /kuljettaja
    restart: always
    ports:
    - 4000:3000
