version: '3'

services:
  proxy:
    image: nginx
    restart: always
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./public:/public:ro
    - output:/output
    ports:
    - 8300:8300
  generator-server:
    image: hsldevcom/hsl-map-generator-server
    restart: always
    environment:
      FONTSTACK_PASSWORD: ${FONTSTACK_PASSWORD}
    ports:
    - 8000:8000
  generator-ui:
    image: hsldevcom/hsl-map-generator-ui
    restart: always
    ports:
    - 3000:3000
  publisher-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
    - 5432
  publisher:
    image: hsldevcom/hsl-map-publisher
    environment:
      PG_CONNECTION_STRING: postgres://postgres:postgres@publisher-postgres:5432/postgres
    depends_on:
    - publisher-postgres
    restart: always
    ports:
    - 4000:4000
    volumes:
    - ./fonts:/fonts:ro
    - output:/output
  publisher-ui:
    image: hsldevcom/hsl-map-publisher-ui
    restart: always
    ports:
    - 5000:5000
  site:
    image: hsldevcom/hsl-map-site
    restart: always
    ports:
    - 5050:4000
  web-ui:
    image: hsldevcom/hsl-map-web-ui
    restart: always
    ports:
    - 4000:3000
  jore-postgis:
    image: mdillon/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
    - 5432
  jore-graphql-import:
    image: hsldevcom/jore-graphql-import
    environment:
      PG_CONNECTION_STRING: postgres://postgres:postgres@jore-postgis:5432/postgres
    depends_on:
    - jore-postgis
  jore-geometry-matcher:
    image: hsldevcom/jore-geometry-matcher
    environment:
      PG_CONNECTION_STRING: postgres://postgres:postgres@jore-postgis:5432/postgres
    depends_on:
    - jore-postgis
  jore-graphql:
    image: hsldevcom/jore-graphql
    restart: always
    environment:
      PG_CONNECTION_STRING: postgres://postgres:postgres@jore-postgis:5432/postgres
    depends_on:
    - jore-postgis
    ports:
    - 8080:5000
  jore-tileserver:
    image: hsldevcom/jore-tileserver
    restart: always
    environment:
      PG_CONNECTION_STRING: postgres://postgres:postgres@jore-postgis:5432/postgres
    depends_on:
    - jore-postgis
    ports:
    - 3000:3000
volumes:
  output: {}
